language: java
# Enable container-based infrastructure
# see https://docs.travis-ci.com/user/reference/overview/
sudo: false

jdk:
  - openjdk8
  - openjdk11

notifications:
  email: false

# Skip the Travis CI's default install command
install: true

script:
- ./mvnw clean verify -Pjdt
