language: java
# Enable container-based infrastructure
# see https://docs.travis-ci.com/user/reference/overview/
sudo: false

jdk:
  - openjdk8
  - openjdk11

# Setting the same var twice in the env actually makes Travis create a matrix
# - i.e. there will be two separate executions, one for each value
env:
  - PROFILE=jdt
  - PROFILE=ij

notifications:
  email: false

# Skip the Travis CI's default install command
install: true

script:
- ./mvnw clean verify -P${PROFILE}
